<?php

/**
 * Implementation of hook_help()
 */
function user_coms_help($path, $args) {
  if ($path == 'admin/help#user_coms') {
    $output = '<p>Module to enabled admins to filter users who completed their user profiles to different completeness levels and send the e-mail messages to encourage them to complete their profiles.</p>';
    return $output;
  }
}

/**
* Implementation of hook_menu
**/
function user_coms_menu() {
	$items = array();

  $items['user_coms/list'] = array(
    'title' => 'Uncompleted Profiles',
    'page callback' => 'user_coms_list_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user_coms/no_profile_pic'] = array(
		'title' => 'List Users - No Profile Picture',
		'page callback' => 'user_coms_no_profile_pic_page',
    'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['user_coms/profile_incomplete'] = array(
		'title' => 'List Users - Profile Incomplete',
		'page callback' => 'user_coms_profile_incomplete_page',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

	$items['user_coms/no_profile_video'] = array(
		'title' => 'List Users - No Profile Video',
		'page callback' => 'user_coms_no_profile_video_page',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

	$items['user_coms/no_showcase'] = array(
		'title' => 'List Users - No Showcase Items',
		'page callback' => 'user_coms_no_showcase_page',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

  $items['user_coms/no_profile_pic_email'] = array(
		'title' => 'E-mail users - No Profile Picture',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_coms_email_body_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

  $items['user_coms/profile_incomplete_email'] = array(
		'title' => 'E-mail users - Profile Incomplete',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_coms_email_body_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

  $items['user_coms/no_profile_video_email'] = array(
		'title' => 'E-mail users - No Profile Video',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_coms_email_body_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

  $items['user_coms/no_showcase_email'] = array(
		'title' => 'E-mail users - No Showcase Items',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_coms_email_body_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

  $items['admin/settings/user_coms'] = array(
		'title' => 'User Communications',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_coms_settings_form'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

/**
* Page Callbacks
*/
function user_coms_no_profile_pic_page($aid) {
  $output .= l('Send E-mail', 'user_coms/no_profile_pic_email');
  $output .= '<p>';
  $result = db_query("SELECT * FROM {content_type_uprofile} INNER JOIN {node} ON {content_type_uprofile}.nid = {node}.nid WHERE {content_type_uprofile}.field_profile_image_list IS NULL");  
  while($object = db_fetch_object($result)) {
    $print_user = user_load($object->uid);
    $output .= theme('username', $print_user).' ('.$print_user->mail.') <br />';
  }

  $output .= '</p>';
  $output .= l('Send E-mail', 'user_coms/no_profile_pic_email');

	return $output;
}

function user_coms_profile_incomplete_page($aid) {
  $output .= l('Send E-mail', 'user_coms/profile_incomplete_email');
  $output .= '<p>';
	$result = db_query("SELECT * FROM {content_complete} INNER JOIN {node} ON {content_complete}.nid = {node}.nid WHERE {content_complete}.completeness < 50");  
  while($object = db_fetch_object($result)) {
    $print_user = user_load($object->uid);
    $output .= theme('username', $print_user).' ('.$print_user->mail.') <br />';
  }

  $output .= '</p>';
  $output .= l('Send E-mail', 'user_coms/profile_incomplete_email');

	return $output;
}

function user_coms_no_profile_video_page($aid) {
  $output .= l('Send E-mail', 'user_coms/no_profile_video_email');
  $output .= '<p>';
	$result = db_query("SELECT * FROM {flag_content} INNER JOIN {node} ON {flag_content}.content_id = {node}.nid WHERE {flag_content}.fid = 5");  
  while($object = db_fetch_object($result)) {
    $print_user = user_load($object->uid);
    $output .= theme('username', $print_user).' ('.$print_user->mail.') <br />';
  }

  $output .= '</p>';
  $output .= l('Send E-mail', 'user_coms/completed_profile_but_no_profile_video_email');

	return $output;
}

function user_coms_no_showcase_page($aid) {
  $output .= l('Send E-mail', 'user_coms/no_showcase_email');
  $output .= '<p>';
	$result = db_query("SELECT * FROM {flag_content} INNER JOIN {node} ON {flag_content}.content_id = {node}.nid WHERE {flag_content}.fid = 5");  
  while($object = db_fetch_object($result)) {
    $print_user = user_load($object->uid);
    $output .= theme('username', $print_user).' ('.$print_user->mail.') <br />';
  }

  $output .= '</p>';
  $output .= l('Send E-mail', 'user_coms/no_showcase_email');

	return $output;
}

function user_coms_list_page($aid) {
  $output .= '<ul>';
  $output .= '<li>'.l('List Users - No Profile Picture', 'user_coms/no_profile_pic').'</li>';
  $output .= '<li>'.l('List Users - Profile Fields Incomplete', 'user_coms/profile_incomplete').'</li>';
  $output .= '<li>'.l('List Users - No Profile Video', 'user_coms/no_profile_video').'</li>';
  $output .= '<li>'.l('List Users - No Showcase Items', 'user_coms/no_showcase').'</li>';  
  $output .= '</ul>';
  
  return $output;
}

/**
 * Implementation of the admin settings form
 */
function user_coms_settings_form() {
	
  $form['user_coms_default_no_profile_pic'] = array(
                '#type' => 'textarea',
                '#title' => 'Default e-mail body for users who haven\'t completed their profiles',
                '#rows' => '5',
                '#default_value' => variable_get('user_coms_default_no_profile_pic'),
  );
  $form['user_coms_default_profile_incomplete'] = array(
                '#type' => 'textarea',
                '#title' => 'Default e-mail body for users who haven\'t completed their profiles',
                '#rows' => '5',
                '#default_value' => variable_get('user_coms_default_profile_incomplete'),
  );
  $form['user_coms_default_no_profile_vid'] = array(
                '#type' => 'textarea',
                '#title' => 'Default e-mail body for users without showcase items',
                '#rows' => '5',
                '#default_value' => variable_get('user_coms_default_no_profile_vid'),
  );
  $form['user_coms_default_no_showcase'] = array(
                '#type' => 'textarea',
                '#title' => 'Default e-mail body for users without showcase items',
                '#rows' => '5',
                '#default_value' => variable_get('user_coms_default_no_showcase'),
  );
  if (module_exists('token')) {
    $form['email_tokens']['token_help'] = array(
      '#title' => t('Replacement patterns'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['email_tokens']['token_help']['help'] = array(
      '#value' => theme('token_help', 'node'),
    );
	}


	return system_settings_form($form);
}

/**
 * Implementation of hook_form for capturing e-mail bodies
*/
function user_coms_email_body_form(&$form_state, $uid) {

  //Set forms default value
  switch(arg(1)) {
		case 'no_profile_pic_email':
      $default_value = variable_get('user_coms_default_no_profile_pic');
      break;
    case 'profile_incomplete_email':
      $default_value = variable_get('user_coms_default_profile_incomplete');
      break;
    case 'no_profile_video_email':
      $default_value = variable_get('user_coms_default_no_profile_vid');
      break;
    case 'no_showcase_email':
      $default_value = variable_get('user_coms_default_no_showcase');
      break;
  }

	$form['#tree'] = TRUE;
	
	$form['email_body'] = array(
		'#type'   => 'textarea',
    '#rows'   => '7',
		'#title'  => t('E-mail body'),
    '#default_value' => $default_value,
	);

  if (module_exists('token')) {
    $form['email_tokens']['token_help'] = array(
      '#title' => t('Replacement patterns'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['email_tokens']['token_help']['help'] = array(
      '#value' => theme('token_help', 'node'),
    );
	}

	$form['submit'] = array(
		'#type'   => 'submit',
		'#value'  => t('Submit'),
	);

	return $form;
}

/**
* Helper functions
*/
function user_coms_get_last_sent($uid) {
  $qresult = db_query("SELECT * FROM {user_coms} WHERE uid = ".$uid);
  if ($qobject = db_fetch_object($qresult)) {
    return $qobject->last_sent;
  }
  else {
    return 0;  
  }
}
/**
* Form submit callback function
*/
function user_coms_email_body_form_submit($form_id, $form_values) {

  $params['email_body'] = $form_values['values']['email_body'];  

  switch(arg(1)) {
		case 'no_profile_pic_email':
      //Run the query to get the e-mail addresses to send to
      $result = db_query("SELECT * FROM {content_type_uprofile} INNER JOIN {node} ON {content_type_uprofile}.nid = {node}.nid WHERE {content_type_uprofile}.field_profile_image_list IS NULL");  
      while($object = db_fetch_object($result)) {
        $mail_user = user_load($object->uid);
        $params['realname'] = $mail_user->realname;
        //Only send e-mail if the user has not received one in the last 30 days
        if(user_coms_get_last_sent($object->uid) < (time() - (30 * 24 * 60 * 60))) {
          drupal_mail('user_coms', 'no_profile_pic', 'williecoetzee@gmail.com', language_default(), $params); 
          //Now add to the db
          //First test if already in db
          $result3 = db_query("SELECT * FROM {user_coms} WHERE uid = ".$object->uid);  
          if (db_fetch_object($result3)) {
            db_query('UPDATE {user_coms} SET email_status = 1, last_sent = '.time().' WHERE uid = '.$object->uid);
          }
          else {
            $data = array(
              'uid' => $object->uid,
              'email_status' => 1,
              'last_sent' => time(),
            );
            drupal_write_record('user_coms', $data);
          }
        }
      } 
      drupal_set_message(t('E-mail sent to those without a profile picture'));
      break;
    case 'profile_incomplete_email':
      //Run the query to get the e-mail addresses to send to
      $result = db_query("SELECT * FROM {content_complete} INNER JOIN {node} ON {content_complete}.nid = {node}.nid WHERE {content_complete}.completeness < 50");  
      while($object = db_fetch_object($result)) {
        $mail_user = user_load($object->uid);
        $params['realname'] = $mail_user->realname;
        //Only send e-mail if the user has not received one in the last 30 days
        if(user_coms_get_last_sent($object->uid) < (time() - (30 * 24 * 60 * 60))) {
          drupal_mail('user_coms', 'profile_incomplete', 'williecoetzee@gmail.com', language_default(), $params); 
          //Now add to the db
          //First test if already in db
          $result3 = db_query("SELECT * FROM {user_coms} WHERE uid = ".$object->uid);  
          if (db_fetch_object($result3)) {
            db_query('UPDATE {user_coms} SET email_status = 2, last_sent = '.time().' WHERE uid = '.$object->uid);
          }
          else {
            $data = array(
              'uid' => $object->uid,
              'email_status' => 2,
              'last_sent' => time(),
            );
            drupal_write_record('user_coms', $data);
          }
        }
      } 
      drupal_set_message(t('E-mail sent to those whos profiles are incomplete'));
      break;
    case 'no_profile_video_email':
      //Run the query to get the e-mail addresses to send to
      $result = db_query("SELECT * FROM {flag_content} INNER JOIN {node} ON {flag_content}.content_id = {node}.nid WHERE {flag_content}.fid = 5");  
      while($object = db_fetch_object($result)) {
        $mail_user = user_load($object->uid);
        $params['realname'] = $mail_user->realname;
        drupal_mail('user_coms', 'no_profile_video', 'williecoetzee@gmail.com', language_default(), $params);
        //Now add to the db
        //First test if already in db
        $result3 = db_query("SELECT * FROM {user_coms} WHERE uid = ".$object->uid);  
        if (db_fetch_object($result3)) {
          db_query('UPDATE {user_coms} SET email_status = 3, last_sent = '.time().' WHERE uid = '.$object->uid);
        }
        else {
          $data = array(
            'uid' => $object->uid,
            'email_status' => 3,
            'last_sent' => time(),
          );
          drupal_write_record('user_coms', $data);
        } 
      } 
      drupal_set_message(t('E-mail sent to those who dont have profile videos'));
      break;
    case 'no_showcase_email':
      //Run the query to get the e-mail addresses to send to
      $result = db_query("SELECT * FROM {flag_content} INNER JOIN {node} ON {flag_content}.content_id = {node}.nid WHERE {flag_content}.fid = 5");  
      while($object = db_fetch_object($result)) {
        $mail_user = user_load($object->uid);
        $params['realname'] = $mail_user->realname;
        drupal_mail('user_coms', 'no_showcase', 'williecoetzee@gmail.com', language_default(), $params); 
        //Now add to the db
        //First test if already in db
        $result3 = db_query("SELECT * FROM {user_coms} WHERE uid = ".$object->uid);  
        if (db_fetch_object($result3)) {
          db_query('UPDATE {user_coms} SET email_status = 4, last_sent = '.time().' WHERE uid = '.$object->uid);
        }
        else {
          $data = array(
            'uid' => $object->uid,
            'email_status' => 4,
            'last_sent' => time(),
          );
          drupal_write_record('user_coms', $data);
        }
      } 
      drupal_set_message(t('E-mail sent to those without showcase items'));
      break;
  }
	drupal_goto('user');
}

/**
* Implementation of hook_mail
*/
function user_coms_mail($key, &$message, $params) {
	switch($key) {
		case 'no_profile_pic':
      $message['subject'] = t('NoJoShmo User Coms');
      $body_string = $params['email_body'];
      $body_string = str_replace('[user_coms:realname]', $params['realname'], $body_string);
      $message['body'][] = $body_string;
      break;
    case 'profile_incomplete':
      $message['subject'] = t('NoJoShmo User Coms');
      $body_string = $params['email_body'];
      $body_string = str_replace('[user_coms:realname]', $params['realname'], $body_string);
      $message['body'][] = $body_string;
      break;
    case 'no_profile_video':
      $message['subject'] = t('NoJoShmo User Coms');
      $body_string = $params['email_body'];
      $body_string = str_replace('[user_coms:realname]', $params['realname'], $body_string);
      $message['body'][] = $body_string;
      break;
    case 'no_showcase':
      $message['subject'] = t('NoJoShmo User Coms');
      $body_string = $params['email_body'];
      $body_string = str_replace('[user_coms:realname]', $params['realname'], $body_string);
      $message['body'][] = $body_string;
      break;
  }
}

function user_coms_token_list($type = 'all') {
    $tokens['global']['user_coms:realname'] = t('The user\'s real name');
    $tokens['global']['user_coms:personal_url'] = t('The user\'s profile URL');
    return $tokens;
  }
