<?php

function user_coms_menu() {
	$items = array();
  $items['user_coms/no_profile_pic'] = array(
		'title' => 'List Users - No Profile Picture',
		'page callback' => 'user_coms_no_profile_pic_page',
    //'page arguments' => array('profile_tmp_access_form', 2),
		//'access arguments' => TRUE,
    'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['user_coms/pic_but_profile_incomplete'] = array(
		'title' => 'List Users - Profile Incomplete',
		'page callback' => 'user_coms_pic_but_profile_incomplete_page',
		//'page arguments' => array(2),
		//'access callback' => '_profile_tmp_access_approve_access',
		'access arguments' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

	$items['user_coms/completed_profile_but_no_profile_video'] = array(
		'title' => 'List Users - No Profile Video',
		'page callback' => 'user_coms_completed_profile_but_no_profile_video_page',
		//'page arguments' => array(2),
		//'access callback' => '_profile_tmp_access_revoke_access',
		'access arguments' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);

	$items['user_coms/no_showcase_items'] = array(
		'title' => 'List Users - No Showcase Items',
		'page callback' => 'user_coms_no_showcase_items_page',
		//'page arguments' => array('profile_tmp_access_settings_form'),
		'access arguments' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
* Page Callbacks
*/
function user_coms_no_profile_pic_page($aid) {
  $result = db_query("SELECT * FROM {content_type_uprofile} INNER JOIN {node} ON {content_type_uprofile}.nid = {node}.nid");
  while($object = db_fetch_object($result)) {
      if($object->field_profile_image_fid.length > 0)  
        $output .= $object->field_profile_image_fid;
      else
        $output .= 'NULL';
  }
	//$output = 'No Profile Pic Page';
	return $output.'1212';
}

function user_coms_pic_but_profile_incomplete_page($aid) {
	$output = 'Profile Incomplete Page';
	return $output;
}

function user_coms_completed_profile_but_no_profile_video_page($aid) {
	$output = 'No Profile Video Page';
	return $output;
}

function user_coms_no_showcase_items_page($aid) {
	$output = 'No Showcase Items Page';
	return $output;
}

